# The host name. This is used to construct the url for the link that appears in
# email notifications
host: localhost

# The port number. This is used to construct the url for the link that appears in
# email notifications
port: 3000

# The email address of the administrator. This email will be used as the "from"
# address in emails sent by openmind.
admin_email: admin@openmind.org

# The subject prefix. This will be the prefix in the subject for emails sent by 
# openmind. For example, "OpenMind: Your new account has been created..."
email_subject_prefix: OpenMind

# The number of minutes until a vote can no longer be rescinded
rescind_minutes: 240

# The default number of days before allocations expire
allocation_expiration_days: 120

# The url to the directory where the images for emails are stored
email_image_url: http://localhost:3000/themes/openmind/images/email

# The name of the theme (e.g., skin). This should correspond to a directory 
# under the public/themes directory
app_theme: openmind

# The number of days within which to warn the user of unused allocations
# about to expire. A value of 0 means never warn the user.
allocation_expiration_warning_days: 45

# The default timezone for new users. Hint: execute the command:
#     rake time:zones:local
# to get a list of timezones local to your location
default_user_timezone: Eastern Time (US & Canada)

# Max file upload size for non-prodmgr and non-sysadmin users (in KB)
max_file_upload_size: 500